version: '3.9'
services:
  mysql:
    image: mysql
    container_name: todo-db
    restart: unless-stopped
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo-go
      - TZ=Asia/Jakarta
